/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkpal;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.Color;
/**
 *
 * @author PC
 */
public class dashboard extends javax.swing.JFrame {
    private static final int CORNER_RADIUS = 30;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        DashboardTab.setSelectedIndex(0);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), CORNER_RADIUS, CORNER_RADIUS));
    }
    @Override
    public void paint(Graphics g) {
        // Paint the JFrame
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.draw(getShape());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollBar1 = new javax.swing.JScrollBar();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        rb_one = new javax.swing.ButtonGroup();
        rb_two = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        DashboardLogo = new javax.swing.JLabel();
        BtnDashboard = new javax.swing.JButton();
        BtnAddCustomer = new javax.swing.JButton();
        BtnAvailableParking = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        DashboardTab = new javax.swing.JTabbedPane();
        Dashboardpanel = new javax.swing.JPanel();
        DashboardLabel = new javax.swing.JLabel();
        DashboardLine = new keeptoo.KGradientPanel();
        AddCusPanel = new javax.swing.JPanel();
        DashboardLine1 = new keeptoo.KGradientPanel();
        DashboardLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mnum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vtype = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        SubmitAddCusBtn = new javax.swing.JButton();
        AvailParkingPanel = new javax.swing.JPanel();
        DashboardLine2 = new keeptoo.KGradientPanel();
        DashboardLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(255, 145, 144));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 145, 144));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(94, 114, 235));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParkPalLogo/ParkPal-Logo9.png"))); // NOI18N
        DashboardLogo.setToolTipText("");
        kGradientPanel1.add(DashboardLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 29, -1, -1));

        BtnDashboard.setBackground(new java.awt.Color(98, 103, 235));
        BtnDashboard.setFont(new java.awt.Font("Poppins Medium", 0, 17)); // NOI18N
        BtnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        BtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/dashboard.png"))); // NOI18N
        BtnDashboard.setText("       DASHBOARD");
        BtnDashboard.setBorder(null);
        BtnDashboard.setContentAreaFilled(false);
        BtnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnDashboardMouseExited(evt);
            }
        });
        BtnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDashboardActionPerformed(evt);
            }
        });
        kGradientPanel1.add(BtnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 249, 255, 46));

        BtnAddCustomer.setBackground(new java.awt.Color(98, 103, 235));
        BtnAddCustomer.setFont(new java.awt.Font("Poppins Medium", 0, 17)); // NOI18N
        BtnAddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/viewparking.png"))); // NOI18N
        BtnAddCustomer.setText("       AVAILABLE PARKING");
        BtnAddCustomer.setActionCommand("         ADD CUSTOMER");
        BtnAddCustomer.setBorder(null);
        BtnAddCustomer.setContentAreaFilled(false);
        BtnAddCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAddCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnAddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAddCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAddCustomerMouseExited(evt);
            }
        });
        BtnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCustomerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(BtnAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 377, 255, 46));

        BtnAvailableParking.setBackground(new java.awt.Color(98, 103, 235));
        BtnAvailableParking.setFont(new java.awt.Font("Poppins Medium", 0, 17)); // NOI18N
        BtnAvailableParking.setForeground(new java.awt.Color(255, 255, 255));
        BtnAvailableParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/addcustomer.png"))); // NOI18N
        BtnAvailableParking.setText("       ADD CUSTOMER");
        BtnAvailableParking.setActionCommand("         ADD CUSTOMER");
        BtnAvailableParking.setBorder(null);
        BtnAvailableParking.setContentAreaFilled(false);
        BtnAvailableParking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAvailableParking.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnAvailableParking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAvailableParkingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAvailableParkingMouseExited(evt);
            }
        });
        BtnAvailableParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAvailableParkingActionPerformed(evt);
            }
        });
        kGradientPanel1.add(BtnAvailableParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 313, 255, 46));

        ExitButton.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("E X I T");
        ExitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        ExitButton.setContentAreaFilled(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 472, 255, 62));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 730));

        DashboardTab.setBackground(new java.awt.Color(255, 255, 255));

        Dashboardpanel.setBackground(new java.awt.Color(255, 255, 255));
        Dashboardpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardLabel.setBackground(new java.awt.Color(255, 255, 255));
        DashboardLabel.setFont(new java.awt.Font("Poppins Medium", 0, 60)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(153, 153, 153));
        DashboardLabel.setText("Dashboard");
        Dashboardpanel.add(DashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 352, 82));

        DashboardLine.setkEndColor(new java.awt.Color(255, 145, 144));
        DashboardLine.setkStartColor(new java.awt.Color(94, 114, 235));

        javax.swing.GroupLayout DashboardLineLayout = new javax.swing.GroupLayout(DashboardLine);
        DashboardLine.setLayout(DashboardLineLayout);
        DashboardLineLayout.setHorizontalGroup(
            DashboardLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        DashboardLineLayout.setVerticalGroup(
            DashboardLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        Dashboardpanel.add(DashboardLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 880, -1));

        DashboardTab.addTab("tab3", Dashboardpanel);

        AddCusPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddCusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardLine1.setkEndColor(new java.awt.Color(255, 145, 144));
        DashboardLine1.setkStartColor(new java.awt.Color(94, 114, 235));

        javax.swing.GroupLayout DashboardLine1Layout = new javax.swing.GroupLayout(DashboardLine1);
        DashboardLine1.setLayout(DashboardLine1Layout);
        DashboardLine1Layout.setHorizontalGroup(
            DashboardLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        DashboardLine1Layout.setVerticalGroup(
            DashboardLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        AddCusPanel.add(DashboardLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 880, -1));

        DashboardLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 60)); // NOI18N
        DashboardLabel1.setForeground(new java.awt.Color(153, 153, 153));
        DashboardLabel1.setText("Add Customer");
        AddCusPanel.add(DashboardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 492, 82));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setText("Given Name:");
        AddCusPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 162, -1, 36));

        fname.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        AddCusPanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 162, 417, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel3.setText("Last Name:");
        AddCusPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 221, -1, 36));

        lname.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        AddCusPanel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 221, 417, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel4.setText("Mobile Number:");
        AddCusPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 275, -1, 36));

        mnum.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        AddCusPanel.add(mnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 275, 417, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel5.setText("Plate Number:");
        AddCusPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 329, -1, 36));

        pnum.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        AddCusPanel.add(pnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 329, 417, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel6.setText("PWD Member or Senior Citizen:");
        AddCusPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 437, -1, 36));

        vtype.setBackground(new java.awt.Color(98, 103, 235));
        vtype.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        vtype.setForeground(new java.awt.Color(255, 255, 255));
        vtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Motorcycle", "4 Wheeler Car" }));
        vtype.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddCusPanel.add(vtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 383, 417, -1));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel7.setText("Vehicle Type:");
        AddCusPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 383, -1, 36));

        rb_one.add(r1);
        r1.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        r1.setText("Yes");
        r1.setBorderPainted(true);
        AddCusPanel.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 438, -1, -1));

        rb_one.add(r2);
        r2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        r2.setText("No");
        AddCusPanel.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 438, -1, -1));

        rb_two.add(p2);
        p2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        p2.setText("No");
        AddCusPanel.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 492, -1, -1));

        rb_two.add(p1);
        p1.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        p1.setText("Yes");
        AddCusPanel.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 492, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel8.setText("Any PWDs or senior citizens in your family?");
        AddCusPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 491, -1, 36));

        SubmitAddCusBtn.setBackground(new java.awt.Color(255, 153, 0));
        SubmitAddCusBtn.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        SubmitAddCusBtn.setForeground(new java.awt.Color(255, 145, 144));
        SubmitAddCusBtn.setText("SUBMIT");
        SubmitAddCusBtn.setBorder(null);
        SubmitAddCusBtn.setContentAreaFilled(false);
        AddCusPanel.add(SubmitAddCusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 170, 60));

        DashboardTab.addTab("tab1", AddCusPanel);

        AvailParkingPanel.setBackground(new java.awt.Color(255, 255, 255));
        AvailParkingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardLine2.setkEndColor(new java.awt.Color(255, 145, 144));
        DashboardLine2.setkStartColor(new java.awt.Color(94, 114, 235));

        javax.swing.GroupLayout DashboardLine2Layout = new javax.swing.GroupLayout(DashboardLine2);
        DashboardLine2.setLayout(DashboardLine2Layout);
        DashboardLine2Layout.setHorizontalGroup(
            DashboardLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        DashboardLine2Layout.setVerticalGroup(
            DashboardLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        AvailParkingPanel.add(DashboardLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 880, -1));

        DashboardLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 60)); // NOI18N
        DashboardLabel2.setForeground(new java.awt.Color(153, 153, 153));
        DashboardLabel2.setText("Available Parking");
        AvailParkingPanel.add(DashboardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 735, 82));

        DashboardTab.addTab("tab2", AvailParkingPanel);

        jPanel1.add(DashboardTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, -38, 910, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 733));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDashboardActionPerformed
        DashboardTab.setSelectedIndex(0);
    }//GEN-LAST:event_BtnDashboardActionPerformed

    private void BtnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCustomerActionPerformed
        DashboardTab.setSelectedIndex(2);
    }//GEN-LAST:event_BtnAddCustomerActionPerformed

    private void BtnAvailableParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAvailableParkingActionPerformed
        DashboardTab.setSelectedIndex(1);
    }//GEN-LAST:event_BtnAvailableParkingActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BtnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDashboardMouseClicked
    }//GEN-LAST:event_BtnDashboardMouseClicked

    private void BtnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDashboardMouseEntered
        BtnDashboard.setForeground(Color.BLACK);
    }//GEN-LAST:event_BtnDashboardMouseEntered

    private void BtnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDashboardMouseExited
        BtnDashboard.setForeground(Color.WHITE);
    }//GEN-LAST:event_BtnDashboardMouseExited

    private void BtnAvailableParkingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAvailableParkingMouseEntered
        BtnAvailableParking.setForeground(Color.BLACK);
    }//GEN-LAST:event_BtnAvailableParkingMouseEntered

    private void BtnAvailableParkingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAvailableParkingMouseExited
        BtnAvailableParking.setForeground(Color.WHITE);
    }//GEN-LAST:event_BtnAvailableParkingMouseExited

    private void BtnAddCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddCustomerMouseEntered
        BtnAddCustomer.setForeground(Color.BLACK);
    }//GEN-LAST:event_BtnAddCustomerMouseEntered

    private void BtnAddCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddCustomerMouseExited
        BtnAddCustomer.setForeground(Color.WHITE);
    }//GEN-LAST:event_BtnAddCustomerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCusPanel;
    private javax.swing.JPanel AvailParkingPanel;
    private javax.swing.JButton BtnAddCustomer;
    private javax.swing.JButton BtnAvailableParking;
    private javax.swing.JButton BtnDashboard;
    private javax.swing.JLabel DashboardLabel;
    private javax.swing.JLabel DashboardLabel1;
    private javax.swing.JLabel DashboardLabel2;
    private keeptoo.KGradientPanel DashboardLine;
    private keeptoo.KGradientPanel DashboardLine1;
    private keeptoo.KGradientPanel DashboardLine2;
    private javax.swing.JLabel DashboardLogo;
    private javax.swing.JTabbedPane DashboardTab;
    private javax.swing.JPanel Dashboardpanel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SubmitAddCusBtn;
    private javax.swing.JTextField fname;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mnum;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JTextField pnum;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.ButtonGroup rb_one;
    private javax.swing.ButtonGroup rb_two;
    private javax.swing.JComboBox<String> vtype;
    // End of variables declaration//GEN-END:variables
}
